version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm-data:/data
      - ./letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "50m"


  # mongodb
  mongodb: 
    image: 'mongo'
    restart: unless-stopped
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./mongo-data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: 'root'
      # MONGO_INITDB_ROOT_PASSWORD: 'slatesyserver12023'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

